title:              Zio Blog
email:              zio0911@naver.com
description:        끄적이는 공간
author:             zio
baseurl:            ""
url:                "https://zio0911.github.io"

# Social Profiles
#twitter_username:   zioscript
github_username:    zio0911
facebook_username:  zioscript
instagram_username:  zio333
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  
  
layout: default
comments: true

disqus_shortname: 'zio blog'
